version: "3.3"
services:
  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data 
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.13.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:8.0.5
    ports:
      - 3000:3000
    volumes: 
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - kibana

